/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.gerenciador.GerenciadorCurso;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evand
 */
public class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        atualizarTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        txtProcurar = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        scpCursos = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        lblProcurar = new javax.swing.JLabel();
        lblNovoCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(34, 47, 132));

        txtProcurar.setBackground(new java.awt.Color(49, 53, 82));
        txtProcurar.setForeground(new java.awt.Color(255, 255, 255));
        txtProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcurarKeyReleased(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(0, 51, 51));
        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(0, 153, 0));
        btnNovo.setText("+");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "CARGA HORÁRIA", "QTD. ALUNOS", "PROFESSOR", "REMOVER", "EDITAR"
            }
        ));
        tblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursosMouseClicked(evt);
            }
        });
        scpCursos.setViewportView(tblCursos);

        lblProcurar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblProcurar.setForeground(new java.awt.Color(255, 255, 255));
        lblProcurar.setText("PROCURAR");

        lblNovoCurso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNovoCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblNovoCurso.setText("NOVO CURSO");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(lblProcurar)
                                .addGap(432, 432, 432)
                                .addComponent(lblNovoCurso))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scpCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcurar)
                    .addComponent(lblNovoCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(scpCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CursoSave telaCadastro = new CursoSave();
        telaCadastro.setVisible(true);
    
    this.atualizarTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursosMouseClicked

        int linha = tblCursos.getSelectedRow();
        int coluna = tblCursos.getSelectedColumn();

        if (linha != -1) {
            try {
                GerenciadorCurso gerenciador = new GerenciadorCurso();
                List<Curso> lista = gerenciador.listarTodos();
                Curso cursoSelecionado = lista.get(linha);

        if (coluna == 4) { 
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente remover o curso de " + cursoSelecionado.getNome() + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (resposta == JOptionPane.YES_OPTION) {
                gerenciador.remover(cursoSelecionado.getId());
                atualizarTabela();
                JOptionPane.showMessageDialog(this, "Curso removido com sucesso!");
            }
            
        } else if (coluna == 5) { 
            JOptionPane.showMessageDialog(this, "Você clicou para editar o curso: " + cursoSelecionado.getNome());
            CursoSave telaEdicao = new CursoSave();
            telaEdicao.preencherParaEdicao(cursoSelecionado);
            telaEdicao.setVisible(true);
            this.dispose();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro na operação: " + e.getMessage());
    }
}
    }//GEN-LAST:event_tblCursosMouseClicked

    private void txtProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcurarKeyReleased
        String termo = txtProcurar.getText();

        try {
            GerenciadorCurso gerenciador = new GerenciadorCurso();
            List<Curso> lista;

            if (termo.trim().isEmpty()) {
                lista = gerenciador.listarTodos();
            } else {
                lista = gerenciador.buscarPorNome(termo);
            }

            DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
            modelo.setNumRows(0);

            for (Curso c : lista) {
                modelo.addRow(new Object[]{
                    c.getNome(),
                    c.getCargaHoraria(),
                    c.getQuantidadeAlunos(),
                    c.getProfessor(),
                    "Remover",
                    "Editar"
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + e.getMessage());
        }
        
    }//GEN-LAST:event_txtProcurarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel lblNovoCurso;
    private javax.swing.JLabel lblProcurar;
    private java.awt.Panel panel1;
    private javax.swing.JScrollPane scpCursos;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabela() {
    try {
        GerenciadorCurso gerenciador = new GerenciadorCurso();
        List<Curso> lista = gerenciador.listarTodos();

        DefaultTableModel modelo = (DefaultTableModel) tblCursos.getModel();
        modelo.setNumRows(0);

        for (Curso c : lista) {
            modelo.addRow(new Object[]{
                c.getNome(),
                c.getCargaHoraria(),
                c.getQuantidadeAlunos(),
                c.getProfessor(),
                "Remover",
                "Editar"
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar os dados: " + e.getMessage());
    }
}

}